// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerceText.CartApi.DbContexts.Models
{
    public partial class Cart
    {
        public Cart()
        {
            CartItems = new HashSet<CartItems>();
        }

        public int Id { get; set; }
        public int UserId { get; set; }

        public virtual ICollection<CartItems> CartItems { get; set; }
    }
}