// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ECommerceText.CartApi.DbContexts.Configurations;
using ECommerceText.CartApi.DbContexts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace ECommerceText.CartApi.DbContexts
{
    public partial class CartDatabaseContext : DbContext
    {
        public CartDatabaseContext()
        {
        }

        public CartDatabaseContext(DbContextOptions<CartDatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CartItems> CartItems { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=CartDatabase;Integrated Security=true");

            modelBuilder.ApplyConfiguration(new Configurations.CartConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CartItemsConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
